project:
  type: website

website:
  title: "Connect Cookbook"
  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar: 
    search: true
    collapse-level: 1
    contents: 
      - section: Server Management
        contents: server
      - section: Content Management
        contents: content
      - section: User/Group Management
        contents: user

format:
  html:
    theme: cosmo
    toc: true
