project:
  type: website

website:
  title: "Connect Cookbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-navigation: true

  sidebar:
    search: true
    collapse-level: 1
    contents:
      - section: "Server Management"
        href: server/index.qmd
        contents:
          - servers/linux-runas-users/index.qmd
          - servers/off-host-environments/index.qmd
          - servers/runtimes/index.qmd
      - section: "Content Management"
        href: content/index.qmd
        contents:
          - content/content-access-all/index.qmd
          - content/content-by-user/index.qmd
          - content/content-permissions/index.qmd
          - content/content-usage/index.qmd
          - content/modify-git/index.qmd
          - content/most-used/index.qmd
          - content/remove-all-content-users/index.qmd
          - content/render-on-demand/index.qmd
          - content/content-runtime/index.qmd
      - text: "User Management"
        href: user/index.qmd
        contents:
          - user/transfer-content/index.qmd

format:
  html:
    theme: cosmo
    toc: true
