project:
  type: website

execute:
  eval: false

website:
  title: "Connect Cookbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-navigation: true

  sidebar:
    search: true
    collapse-level: 1
    file: index.qmd
    contents:
      - section: "Getting Started"
        file: ./01-getting-started/index.qmd
        contents:
        - ./01-getting-started/01-installing-the-posit-sdk/index.qmd
        - ./01-getting-started/02-creating-an-api-key/index.qmd
        - ./01-getting-started/03-initializing-a-client/index.qmd
      # - section: "Users"
      #   file: ./02-users/index.qmd
      #   contents:
      #   - ./02-users/01-viewing-user-information/index.qmd
      #   - ./02-users/02-finding-users/index.qmd
      #   - ./02-users/03-finding-users-using-a-remote-authentication-provider-ldap-/index.qmd
      #   - ./02-users/04-creating-a-user-using-password-authentication/index.qmd
      #   - ./02-users/05-creating-a-user-using-pam-authentication/index.qmd
      #   - ./02-users/06-creating-a-user-using-oauth2-authentication/index.qmd
      #   - ./02-users/07-creating-a-user-using-google-oauth2-authentication/index.qmd
      #   - ./02-users/08-creating-a-user-using-proxied-authentication/index.qmd
      #   - ./02-users/09-creating-a-user-using-a-remote-authentication-provider-ldap-/index.qmd
      #   - ./02-users/10-updating-a-user/index.qmd
      #   - ./02-users/11-locking-a-user/index.qmd
      - section: "Groups"
        file: ./03-groups/index.qmd
        contents:
        - ./03-groups/01-viewing-group-information/index.qmd
        - ./03-groups/02-finding-groups/index.qmd
        # - ./03-groups/03-finding-groups-using-a-remote-authentication-provider-ldap-/index.qmd
        # - ./03-groups/04-creating-a-group-using-password-authentication/index.qmd
        # - ./03-groups/05-creating-a-group-using-pam-authentication/index.qmd
        # - ./03-groups/06-creating-a-group-using-oauth2-authentication/index.qmd
        # - ./03-groups/07-creating-a-group-using-google-oauth2-authentication/index.qmd
        # - ./03-groups/08-creating-a-group-using-proxied-authentication/index.qmd
        # - ./03-groups/09-creating-a-group-using-a-remote-authentication-provider-ldap-/index.qmd
        # - ./03-groups/10-finding-group-members/index.qmd
        # - ./03-groups/11-create-group-members/index.qmd
        # - ./03-groups/12-deleting-group-members/index.qmd
        # - ./03-groups/13-analyzing-group-members/index.qmd
      - section: "Content"
        # file: ./04-content/index.qmd
        contents:
      #   - ./04-content/01-viewing-content-information/index.qmd
        - ./04-content/02-viewing-content-runtime-settings/index.qmd
      #   - ./04-content/03-viewing-content-git-repository-settings/index.qmd
      #   - ./04-content/04-viewing-content-vanity-urls/index.qmd
        # - ./04-content/05-finding-content/index.qmd
        - ./04-content/06-finding-public-content/index.qmd
      #   - ./04-content/07-finding-authorized-content/index.qmd
      #   - ./04-content/08-finding-content-owned-by-a-user/index.qmd
      #   - ./04-content/09-creating-content/index.qmd
      #   - ./04-content/10-creating-content-git-repository-settings/index.qmd
      #   - ./04-content/11-creating-content-vanity-urls/index.qmd
      #   - ./04-content/12-updating-content/index.qmd
      #   - ./04-content/13-updating-content-git-repository-settings/index.qmd
      #   - ./04-content/14-deleting-content/index.qmd
      #   - ./04-content/15-deleting-content-git-repository-settings/index.qmd
      #   - ./04-content/16-deleting-content-vanity-urls/index.qmd
      #   - ./04-content/17-duplicating-content/index.qmd
      # - section: "Content Access Controls"
      #   file: ./05-content-access-controls/index.qmd
      #   contents:
      #   - ./05-content-access-controls/01-analyzing-content-ownership/index.qmd
      #   - ./05-content-access-controls/02-transferring-content-ownership/index.qmd
      #   - ./05-content-access-controls/03-granting-access-to-a-user/index.qmd
      #   - ./05-content-access-controls/04-granting-access-to-a-group/index.qmd
      #   - ./05-content-access-controls/05-revoking-access-from-users/index.qmd
      #   - ./05-content-access-controls/06-revoking-access-from-viewers/index.qmd
      #   - ./05-content-access-controls/07-revoking-access-from-collaborators/index.qmd
      #   - ./05-content-access-controls/08-revoking-access-from-groups/index.qmd
      # - section: "Content Organization"
      #   file: ./06-content-organization/index.qmd
      #   contents:
      #   - ./06-content-organization/01-viewing-tag-information/index.qmd
      #   - ./06-content-organization/02-viewing-tags-by-content/index.qmd
      #   - ./06-content-organization/03-creating-tags/index.qmd
      #   - ./06-content-organization/04-assigning-tags/index.qmd
      #   - ./06-content-organization/05-deleting-tags/index.qmd
      # - section: "Bundles"
      #   file: ./07-bundles/index.qmd
      #   contents:
      #   - ./07-bundles/01-viewing-bundle-information/index.qmd
      #   - ./07-bundles/02-finding-bundles/index.qmd
      #   - ./07-bundles/03-creating-bundles/index.qmd
      #   - ./07-bundles/04-deleting-bundles/index.qmd
      #   - ./07-bundles/05-downloading-bundles/index.qmd
      #   - ./07-bundles/06-deploying-bundles/index.qmd
      # - section: "Tasks"
      #   file: ./08-tasks/index.qmd
      #   contents:
      #   - ./08-tasks/01-viewing-task-information/index.qmd
      # - section: "Jobs"
      #   file: ./09-jobs/index.qmd
      #   contents:
      #   - ./09-jobs/01-viewing-job-information/index.qmd
      #   - ./09-jobs/02-viewing-jobs-by-content/index.qmd
      #   - ./09-jobs/03-viewing-job-logs/index.qmd
      #   - ./09-jobs/04-viewing-job-errors/index.qmd
      #   - ./09-jobs/05-registering-a-job-kill-order/index.qmd
      - section: "Server Management"
        file: ./10-server-management/index.qmd
        contents:
      #   - ./10-server-management/01-bootstrapping-the-server/index.qmd
      #   - ./10-server-management/02-viewing-the-server-version/index.qmd
      #   - ./10-server-management/03-viewing-runtime-users/index.qmd
      #   - ./10-server-management/04-viewing-python-runtime-installations/index.qmd
      #   - ./10-server-management/05-viewing-r-runtime-installations/index.qmd
      #   - ./10-server-management/06-viewing-quarto-runtime-installations/index.qmd
      #   - ./10-server-management/07-viewing-tensorflow-installations/index.qmd
      #   - ./10-server-management/08-viewing-feature-flags/index.qmd
      #   - ./10-server-management/09-analyzing-runtime-users/index.qmd
        - ./10-server-management/10-viewing-runtime-caches/index.qmd
        - ./10-server-management/11-deleting-runtime-caches/index.qmd
      # - section: "Off Host Execution"
      #   file: ./11-off-host-execution/index.qmd
      #   contents:
      #   - ./11-off-host-execution/01-viewing-container-images/index.qmd
      #   - ./11-off-host-execution/02-viewing-execution-environments/index.qmd
      #   - ./11-off-host-execution/03-creating-execution-environments/index.qmd
      #   - ./11-off-host-execution/04-updating-execution-environments/index.qmd
      #   - ./11-off-host-execution/05-deleting-execution-environments/index.qmd
      #   - ./11-off-host-execution/06-analyzing-execution-environments/index.qmd
      # - section: "Auditing"
      #   file: ./12-auditing/index.qmd
      #   contents:
      #   - ./12-auditing/01-viewing-audit-logs/index.qmd
      #   - ./12-auditing/02-analyzing-audit-logs/index.qmd
      # - section: "Metrics"
      #   file: ./13-metrics/index.qmd
      #   contents:
      #   - ./13-metrics/01-viewing-content-usage-information/index.qmd
      #   - ./13-metrics/02-analyzing-content-usage-information/index.qmd
      #   - ./13-metrics/03-analyzing-popular-content/index.qmd
      #   - ./13-metrics/04-analyzing-popular-publishers/index.qmd
      # - section: "MLOps"
      #   file: ./14-mlops/index.qmd
      #   contents:
      #   - ./14-mlops/01-deploying-content/index.qmd
      #   - ./14-mlops/02-rendering-content-on-demand/index.qmd
      #   - ./14-mlops/03-promoting-content/index.qmd
      #   - ./14-mlops/04-blue-green-deployments/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-expand: 3
