project:
  type: website

website:
  title: "Connect Cookbook"
  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar: 
    style: "docked"
    search: true
    contents: 
      - section: Server Management
        contents: server-level
      - section: Content Management
        contents: content-level
      - section: User/Group Management
        contents: user-level

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true