project:
  type: website

execute:
  eval: false

website:
  title: "Connect Cookbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-navigation: true

  sidebar:
    search: true
    collapse-level: 1
    contents: /**/**/*.qmd

format:
  html:
    theme: cosmo
    toc: true
