project:
  type: website

execute:
  eval: false

website:
  title: "Connect Cookbook"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-navigation: true

  sidebar:
    search: true
    collapse-level: 2
    file: index.qmd
    contents:
      - section: "Getting Started"
        file: ./getting-started/index.qmd
        contents:
        - ./getting-started/installing-the-posit-sdk/index.qmd
        - ./getting-started/creating-an-api-key/index.qmd
        - ./getting-started/initializing-a-client/index.qmd
      - section: "Users"
        file: ./users/index.qmd
        contents:
        - ./users/viewing-user-information/index.qmd
        - ./users/finding-users/index.qmd
        - ./users/finding-licensed-users/index.qmd
      #   - ./users/finding-users-using-a-remote-authentication-provider-ldap/index.qmd
      #   - ./users/creating-a-user-using-password-authentication/index.qmd
      #   - ./users/creating-a-user-using-pam-authentication/index.qmd
      #   - ./users/creating-a-user-using-oauth2-authentication/index.qmd
      #   - ./users/creating-a-user-using-google-oauth2-authentication/index.qmd
      #   - ./users/creating-a-user-using-proxied-authentication/index.qmd
        - ./users/creating-a-user-using-a-remote-authentication-provider-ldap/index.qmd
      #   - ./users/updating-a-user/index.qmd
      #   - ./users/locking-a-user/index.qmd
      - section: "Groups"
        file: ./groups/index.qmd
        contents:
        - ./groups/viewing-group-information/index.qmd
        - ./groups/finding-groups/index.qmd
        # - ./groups/finding-groups-using-a-remote-authentication-provider-ldap/index.qmd
        # - ./groups/creating-a-group-using-password-authentication/index.qmd
        # - ./groups/creating-a-group-using-pam-authentication/index.qmd
        # - ./groups/creating-a-group-using-oauth2-authentication/index.qmd
        # - ./groups/creating-a-group-using-google-oauth2-authentication/index.qmd
        # - ./groups/creating-a-group-using-proxied-authentication/index.qmd
        - ./groups/creating-a-group-using-a-remote-authentication-provider-ldap/index.qmd
        # - ./groups/finding-group-members/index.qmd
        # - ./groups/create-group-members/index.qmd
        # - ./groups/deleting-group-members/index.qmd
        # - ./groups/analyzing-group-members/index.qmd
      - section: "Content"
        file: ./content/index.qmd
        contents:
        - ./content/viewing-content-information/index.qmd
        - ./content/viewing-content-runtime-settings/index.qmd
      #   - ./content/viewing-content-git-repository-settings/index.qmd
        - ./content/viewing-all-vanity-urls/index.qmd
        # - ./content/finding-content/index.qmd
        - ./content/finding-public-content/index.qmd
      #   - ./content/finding-authorized-content/index.qmd
        - ./content/finding-content-owned-by-a-user/index.qmd
        - ./content/finding-content-by-tag/index.qmd
      #   - ./content/creating-content/index.qmd
      #   - ./content/creating-content-git-repository-settings/index.qmd
        # - ./content/creating-content-git-repository-settings/index.qmd
        - ./content/setting-a-content-items-vanity-url/index.qmd
      #   - ./content/updating-content/index.qmd
        - ./content/updating-content-git-repository-settings/index.qmd
      #   - ./content/deleting-content/index.qmd
      #   - ./content/deleting-content-git-repository-settings/index.qmd
        - ./content/deleting-a-content-items-vanity-url/index.qmd
      #   - ./content/duplicating-content/index.qmd
        - ./content/viewing-a-content-items-vanity-url/index.qmd
      - section: "Content Access Controls"
        file: ./content-access-controls/index.qmd
        contents:
      #   - ./content-access-controls/analyzing-content-ownership/index.qmd
        - ./content-access-controls/transferring-content-ownership/index.qmd
        - ./content-access-controls/granting-access-to-a-user/index.qmd
        - ./content-access-controls/granting-access-to-a-group/index.qmd
        - ./content-access-controls/revoking-access-from-a-user/index.qmd
      #   - ./content-access-controls/revoking-access-from-viewers/index.qmd
      #   - ./content-access-controls/revoking-access-from-collaborators/index.qmd
        - ./content-access-controls/revoking-access-from-a-group/index.qmd
        - ./content-access-controls/auditing-group-access-to-content/index.qmd
        - ./content-access-controls/revoking-all-access-except-the-content-owner/index.qmd
      - section: "Content Organization"
        file: ./content-organization/index.qmd
        contents:
        - ./content-organization/viewing-tag-information/index.qmd
        - ./content-organization/viewing-tags-by-content/index.qmd
        - ./content-organization/creating-tags/index.qmd
        - ./content-organization/assigning-tags/index.qmd
        - ./content-organization/deleting-tags/index.qmd
      # - section: "Bundles"
      #   file: ./bundles/index.qmd
      #   contents:
      #   - ./bundles/viewing-bundle-information/index.qmd
      #   - ./bundles/finding-bundles/index.qmd
      #   - ./bundles/creating-bundles/index.qmd
      #   - ./bundles/deleting-bundles/index.qmd
      #   - ./bundles/downloading-bundles/index.qmd
      #   - ./bundles/deploying-bundles/index.qmd
      # - section: "Tasks"
      #   file: ./tasks/index.qmd
      #   contents:
      #   - ./tasks/viewing-task-information/index.qmd
      - section: "Jobs"
        file: ./jobs/index.qmd
        contents:
      #   - ./jobs/viewing-job-information/index.qmd
        - ./jobs/viewing-jobs-for-content/index.qmd
      #   - ./jobs/viewing-job-logs/index.qmd
      #   - ./jobs/viewing-job-errors/index.qmd
        - ./jobs/registering-a-job-kill-order/index.qmd
      - section: "Server Management"
        file: ./server-management/index.qmd
        contents:
      #   - ./server-management/bootstrapping-the-server/index.qmd
      #   - ./server-management/viewing-the-server-version/index.qmd
        - ./server-management/viewing-content-runtime-settings/index.qmd
        - ./server-management/viewing-available-python-r-quarto-runtime-versions/index.qmd
      #   - ./server-management/viewing-feature-flags/index.qmd
        - ./server-management/finding-content-with-custom-runtime-settings/index.qmd
        - ./server-management/viewing-runtime-caches/index.qmd
        - ./server-management/deleting-runtime-caches/index.qmd
      - section: "Off Host Execution"
        file: ./off-host-execution/index.qmd
        contents:
        - ./off-host-execution/viewing-container-image-usage/index.qmd
        - ./off-host-execution/viewing-execution-environment-runtimes/index.qmd
        - ./off-host-execution/creating-execution-environments/index.qmd
      #   - ./off-host-execution/updating-execution-environments/index.qmd
      #   - ./off-host-execution/deleting-execution-environments/index.qmd
        - ./off-host-execution/finding-all-content-using-an-image/index.qmd
      # - section: "Auditing"
      #   file: ./auditing/index.qmd
      #   contents:
      #   - ./auditing/viewing-audit-logs/index.qmd
        # - ./auditing/analyzing-audit-logs/index.qmd
      - section: "Metrics"
        file: ./metrics/index.qmd
        contents:
        - ./metrics/viewing-content-usage-information/index.qmd
        - ./metrics/analyzing-usage-statistics-for-a-content-item/index.qmd
      #   - ./metrics/analyzing-popular-content/index.qmd
      #   - ./metrics/analyzing-popular-publishers/index.qmd
        - ./metrics/analyzing-most-active-content-users-and-publishers/index.qmd
      - section: "Operations"
        file: ./operations/index.qmd
        contents:
        - ./operations/deploying-content/index.qmd
        # - ./operations/rendering-content-on-demand/index.qmd
        - ./operations/promoting-content-from-staging-to-production/index.qmd
        - ./operations/blue-green-deployments/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-expand: 3
