---
title: "Assigning tags"
execute:
    eval: false
---

## Description

You want to assign a tag content item.

::: {.callout-tip}

A tag must be [created](../create/index.qmd) before it can be assigned to content.

:::


## Recipe: Assign a tag

A content identifier and tag identifier are required to assign a tag.

::: {.callout-warning}

You must have administrator privileges to assign a tag.

:::

::: {.panel-tabset group="language"}

## Python

### Prerequisites

Before executing, ensure you have the following information:

- The unique identifier (GUID) for the content item you want to tag. See [Content] recipes, or copy the GUID from the Info pane in the Connect Dashboard.
- The unique identifier the tag you want to use. See the [Find tags](../find/index.qmd) recipe for details.

```{.python}
from posit import connect
client = connect.Client()

content_guid = 'your-content-item-guid'
tag_id = "your-tag-id"

client.post(f"/v1/content/{content_guid}/tags", json={
    'tag_id': tag_id,
})
```

::: {.callout-tip}

See [*Finding tags*](../find/index.qmd) to learn how to view the tags for a content item.

:::

## R

### Prerequisites

Before executing, ensure you have the following information:

- The unique identifier (GUID) for the content item you want to tag. See [Content] recipes, or copy the GUID from the Info pane in the Connect Dashboard.
- The name or identifier of the tag you wish to find. See the [Find tags](../find/index.qmd) recipe for details.

### Code

The `set_content_tags()` function in `connectapi` can take multiple tag objects, and returns an object representing the updated content item.

```{.r}
library(connectapi)
client <- connect()

# Create an object representing the content you wish to update.
content_guid <- "154bd2af-e8fa-4aa4-aab8-dcef701f4af9"
target_content <- get_content(client, guid = content_guid)

# Get the tags from the Connect server, then specify the tag you wish to apply
# to the content.
tags <- get_tags(client)
target_tag <- tags$category$my_tag

target_content <- set_content_tags(content = target_content, tag = target_tag)
```

### Expected Output

```{.r}
> item <- set_content_tags(target_content, target_tag)
Posit Connect Tag Tree (target_content)
└── category
   └── my_tag

> item
Posit Connect Content: 
  Content GUID: 154bd2af-e8fa-4aa4-aab8-dcef701f4af9
  Content URL: https://connect.example.org/connect/#/apps/154bd2af-e8fa-4aa4-aab8-dcef701f4af9/
  Content Title: Public Content States

content_item(client, guid = "154bd2af-e8fa-4aa4-aab8-dcef701f4af9")
```

:::

#### See Also

- [Content](../../content/index.qmd)
- [Tags](../index.qmd)
